/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazurl3ia.project.ui.tests;

import com.google.inject.Injector;
import fr.univcotedazurl3ia.project.ChartCS.ui.internal.ChartCSActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ChartItUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ChartCSActivator.getInstance().getInjector("fr.univcotedazurl3ia.project.ChartIt");
	}

}
