/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazurl3ia.project.ide;


/**
 * Use this class to register ide components.
 */
public class ChartItIdeModule extends AbstractChartItIdeModule {
}
