/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazurl3ia.project.parser.antlr;

import com.google.inject.Inject;
import fr.univcotedazurl3ia.project.parser.antlr.internal.InternalChartItParser;
import fr.univcotedazurl3ia.project.services.ChartItGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ChartItParser extends AbstractAntlrParser {

	@Inject
	private ChartItGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalChartItParser createParser(XtextTokenStream stream) {
		return new InternalChartItParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public ChartItGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ChartItGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
