/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazurl3ia.project.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ChartItAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/univcotedazurl3ia/project/parser/antlr/internal/InternalChartIt.tokens");
	}
}
