/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazurl3ia.project;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ChartItStandaloneSetup extends ChartItStandaloneSetupGenerated {

	public static void doSetup() {
		new ChartItStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
