/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazurl3ia.project.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractChartItScopeProvider extends DelegatingScopeProvider {
}
